artifact_uri: file:///home/mle-user/mle-mlflow-1/mlflow_experiments_store/0/4e54164b768143df9c6acbe6cfa60439/artifacts
end_time: 1773325962592
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 4e54164b768143df9c6acbe6cfa60439
run_name: Default
run_uuid: 4e54164b768143df9c6acbe6cfa60439
source_name: ''
source_type: 4
source_version: ''
start_time: 1773325962584
status: 3
tags: []
user_id: mle-user
