artifact_uri: file:///home/mle-user/mle-mlflow-1/mlflow_experiments_store/0/c0f757c5f1ee4627b942f11dba1275a8/artifacts
end_time: 1773325531278
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: c0f757c5f1ee4627b942f11dba1275a8
run_name: Default
run_uuid: c0f757c5f1ee4627b942f11dba1275a8
source_name: ''
source_type: 4
source_version: ''
start_time: 1773325531271
status: 3
tags: []
user_id: mle-user
